@echo off
echo Cleaning up Screenpipe data directory...
set SCREENPIPE_DATA=%USERPROFILE%\.screenpipe\data
echo Stopping Screenpipe service...
taskkill /F /IM screenpipe.exe 2>nul
timeout /t 2 /nobreak >nul
echo Removing corrupted MP4 files...
del /q "%SCREENPIPE_DATA%\*.mp4" 2>nul
echo Restarting Screenpipe...
start "" screenpipe
echo Cleanup complete.
